# Generated by Django 3.0.2 on 2020-03-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('image', models.ImageField(upload_to='pics')),
                ('post_text', models.TextField()),
                ('trending', models.BooleanField(default=False)),
            ],
        ),
    ]
