# Generated by Django 3.0.2 on 2020-04-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='month',
            field=models.CharField(max_length=10),
        ),
    ]
